releases:
  - name: productcatalogservice
    chart: ../charts/backend
    version: 0.1.0
    namespace: onlineboutique
    values:
    - ./productcatalogservice.yaml

  - name: adservice
    chart: ../charts/backend
    version: 0.1.0
    namespace: onlineboutique
    values:
    - ./adservice.yaml

  - name: cartservice
    chart: ../charts/backend
    version: 0.1.0
    namespace: onlineboutique
    values:
    - ./cartservice.yaml

  - name: checkoutservice
    chart: ../charts/backend
    version: 0.1.0
    namespace: onlineboutique
    values:
    - ./checkoutservice.yaml

  - name: currencyservice
    chart: ../charts/backend
    version: 0.1.0
    namespace: onlineboutique
    values:
    - ./currencyservice.yaml

  - name: emailservice
    chart: ../charts/backend
    version: 0.1.0
    namespace: onlineboutique
    values:
    - ./emailservice.yaml

  - name: paymentservice
    chart: ../charts/backend
    version: 0.1.0
    namespace: onlineboutique
    values:
    - ./paymentservice.yaml

  - name: recommendationservice
    chart: ../charts/backend
    version: 0.1.0
    namespace: onlineboutique
    values:
    - ./recommendationservice.yaml

  - name: shippingservice
    chart: ../charts/backend
    version: 0.1.0
    namespace: onlineboutique
    values:
    - ./shippingservice.yaml

  - name: frontend
    chart: ../charts/backend
    version: 0.1.0
    namespace: onlineboutique
    values:
    - ./frontend.yaml

  - name: loadgenerator
    chart: ../charts/backend
    version: 0.1.0
    namespace: onlineboutique
    values:
    - ./loadgenerator.yaml

  - name: redis
    chart: oci://registry-1.docker.io/bitnamicharts/redis
    version: 20.7.0
    namespace: onlineboutique
    values:
      - ./redis.yaml
