fullnameOverride: "productcatalogservice"

image:
  registry: us-central1-docker.pkg.dev
  repository: google-samples/microservices-demo/productcatalogservice
  tag: "v0.10.2"

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

networkPolicy:
  enabled: true
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: frontend
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: checkoutservice
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: recommendationservice
    ports:
     - port: 3550
       protocol: TCP

env:
  - name: COLLECTOR_SERVICE_ADDR
    value: "jaegertracing-collector.obs-tracing.svc.cluster.local:4317"
  - name: ENABLE_TRACING
    value: "1"
  - name: OTEL_SERVICE_NAME
    value: "productcatalogservice"
  - name: EXTRA_LATENCY
    value: "0"
  - name: DISABLE_PROFILER
    value: "1"

service:
  type: ClusterIP
  port: 3550
  portName: grpc

readinessProbe:
  grpc:
    port: 3550

livenessProbe:
  grpc:
    port: 3550
