server:
  retention: "1h"
  retentionSize: "2GB"

  persistentVolume:
    enabled: false

  remoteWrite:
    - url: http://cortex-nginx.obs-cortex.svc.cluster.local/api/v1/push

alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

pushgateway:
  enabled: false

