environments: 
  default:
    values:
    - ./values.yaml
---
helmfiles:
  - ./obs-storage/helmfile.yaml
  - ./obs-metric/helmfile.yaml
  - ./obs-log/helmfile.yaml
  - ./obs-linkerd/helmfile.yaml
  - ./obs-tracing/helmfile.yaml
  - ./obs-dashboard/helmfile.yaml
