repositories:
  - name: cortex-helm
    url: https://cortexproject.github.io/cortex-helm-chart
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

hooks:
  - events: ["prepare"]
    showlogs: true
    command: kubectl
    args:
    - "apply"
    - "--server-side"
    - "-k"
    - "."

environments: 
  default:
    values:
    - ../values.yaml
---

releases:
  - name: prometheus
    chart: prometheus-community/kube-prometheus-stack
    namespace: obs-metric
    createNamespace: true
    version: 69.2.4
    values:
    - ./prometheus-stack.yaml
    labels:
      layer: metric

  - name: cortex
    chart: cortex-helm/cortex
    namespace: obs-metric
    createNamespace: true
    version: 2.5.0
    values:
    - ./cortex.yaml.gotmpl
    labels:
      layer: metric

