repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

environments: 
  default:
    values:
    - ../values.yaml
---

releases:
  - name: loki
    chart: grafana/loki
    version: 6.25.1
    namespace: obs-log
    createNamespace: true
    values:
    - ./loki.yaml.gotmpl
    labels:
      layer: log

  - name: alloy
    chart: grafana/alloy
    version: 0.11.0
    namespace: obs-log
    createNamespace: true
    values:
    - ./alloy.yaml
    labels:
      layer: log
