repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: grafana
    chart: grafana/grafana
    namespace: obs-ui
    createNamespace: true
    values:
    - ./grafana.yaml.gotmpl
